<?php
abstract class BasePresenter extends \Nette\Application\UI\Presenter
{
  /**
  * Preview action for texyla. This generate preview. 
  */
  public function actionPreview()
  {
    $post = $this->context->getService("httpRequest")->getPost("texy");
    $html = \Nette\Utils\Strings::trim($this->context->texy->process($post));
    $response = new \Nette\Application\Responses\TextResponse($html);
    $this->sendResponse($response);
  }
  
  /**
  * Handle sign out. Function is accessable in all web. */
  public function handleSignout()
  {
    $this->getUser()->logout();
    $this->flashMessage("Byl jste odhlášen.", "success");
    $this->redirect("Homepage:");
  }
  
  /**
  * Css loader factory
  * @return CssLoader */
  public function createComponentCss()
  {
    return new \WebLoader\Nette\CssLoader(
      $this->context->webloader->cssDefaultCompiler, // service generated by extension
      $this->template->basePath . '/webtemp'
    );
  }
  
    /**
  * Js loader factory
  * @return JsLoader */
  public function createComponentJs()
  {
    return new \WebLoader\Nette\JavaScriptLoader(
      $this->context->webloader->jsDefaultCompiler, // service generated by extension
      $this->template->basePath . '/webtemp'
    );
  }
  
    /**
     * Texyla loader factory
     * @return TexylaLoader */
  protected function createComponentTexyla()
  {
    baseUri = $this->context->httpRequest->url->baseUrl;
    $filter = new \WebLoader\Filter\VariablesFilter(array(
      "baseUri" => $baseUri ,
      "previewPath" => $this->link("preview"), )
    );
  
    $texyla = new TexylaLoader($filter, $baseUri."webtemp");
    return $texyla;
  }
}
